export const data = [{
  selectedProduct:{
    logo: "/images/adidas.jpg",
    description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
    category: "Men",
    rate: 4.5,
    nomOfRates:"22",
    price:"9,999",
    salePrice: 8999,
    salePercent:"30",
    size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
    color: ['Black', 'White'],
    img: [
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQQABgCREGYuDtbMirGxboOdRMPPeJFXPEkg&usqp=CAU',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7oAiP2hH4MYw-SFOsZrxxJCzntdb0q_ERKQ&usqp=CAU',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR3zmIlBTauQHlPXPsJX7QCVK1qFsuW82kvw&usqp=CAU',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVPGD9GPay3SFjne6H8BBkvT5cWoQ6FDRoKA&usqp=CAU',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnS78Zif8hVSSI8fBuvVJgnA4pQbwX_YZCOA&usqp=CAU',
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8K89z7UlHz3ErplJ8e3gsLfEJ5_3jYUTG9g&usqp=CAU',
        ]
    },
    similarProducts: [{
        logo: "/images/adidas.jpg",
        description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        category: "Men",
        rate: 3.5,
        nomOfRates:"22",
        price:"9,999",
        salePrice:"8,999",
        salePercent:"30",
        size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
        color: ['Black', 'white'],
        img: 'https://knoww.cc/wp-content/uploads/2019/07/10405.jpg',
        location: 'Pickup From Mall of Arab'
    },
    {
        logo: "/images/adidas.jpg",
        description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        category: "Men",
        rate: 4,
        nomOfRates:"22",
        price:"9,999",
        salePrice:"8,999",
        salePercent:"30",
        size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
        color: ['Black', 'white'],
        img: 'https://7loo.net/wp-content/uploads/2019/08/2654-11.jpg',
        location: 'Pickup From Mall of Egypt'
    },
    {
        logo: "/images/adidas.jpg",
        description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        category: "Men",
        rate: 5,
        nomOfRates:"12",
        price:"9,699",
        salePrice:"8,899",
        salePercent:"50",
        size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
        color: ['Black', 'white'],
        img: 'https://i.pinimg.com/736x/e9/66/77/e9667798dcaa2d34130c4c40e6f9bb65--adidas-clothes-adidas-mens-clothing.jpg',
        location: 'Pickup From Mall of Egypt'
    },
    {   
        logo: "/images/adidas.jpg",
        description: "Adidas black t-shirt Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        category: "Men",
        rate: 2.5,
        nomOfRates:"22",
        price:"9,999",
        salePrice:"8,999",
        salePercent:"30",
        size: ['Small', 'Medium', 'Large', 'XLarge', 'XXLarge'],
        color: ['Black', 'white'],
        img: 'https://eyess.cc/wp-content/uploads/2019/08/1815-8.jpg',
        location: 'Pickup From Mall of Egypt'
    }]
}];